### ISSUE TITLE
GeoRedundancy

### ISSUE THREAD

**Issue by willstg** [Azure/classic-iaas-resourcemanager-migration#24]
Hello,

New to GitHub, my use of issues.   I have a Georedundant deployment and it would be great MigAz take into consideration the Regional properties of the subscription.  This would require at least one ResourceGroup, per location associated with a subscription.  

Thanks!  Keep up the great work.

Will.

**Comment by singhkays** [comment]
Adding @PauloRamosGit

**Comment by PauloRamosGit** [comment]
Hi Will,
Thank you for using migAz.
Can you provide some more detail on what you are aiming?

In my current understanding I would say that you should use migAz to export an ARM template per each location that your deployment have.

Let me know.

**Comment by willstg** [comment]
Good point.  Sorry I got busy...working my migration again today.
