### ISSUE TITLE
Authentication with a PIN causes an error

### ISSUE THREAD

**Issue by willstg** [Azure/classic-iaas-resourcemanager-migration#28]
![image](https://cloud.githubusercontent.com/assets/8040704/19388362/774eb812-91dc-11e6-85b5-d2642ad7924a.png)

**Comment by willstg** [comment]
Nevermind...this happens on native powershell too...must be me :)

**Comment by singhkays** [comment]
@willstg Do you by chance have Fiddler running in the background?
