### ISSUE TITLE
Location setting only affects Resource Group

### ISSUE THREAD

**Issue by ssugar** [Azure/classic-iaas-resourcemanager-migration#31]
There is an option to set the Location when generating the instructions. 

That Location option only sets the location for the Resource Group.  All resources within that group are created into the location they were in before.

It's a bit misleading.   If someone sets the location option to West US, and all actual resources are created in East US, it causes confusion.

Workaround for me was to go in and manually change the export.json file to create all resources into the desired location.

**Comment by ruandersMSFT** [comment]
I concur with the stated issue in that the generated JSON doesn't reflect the desired *target* location; rather, it exports the same data center location that the resources are sourced from.  The existing location of input for the target data center (occurring after the export has actually occurred), doesn't allow for the selection to be represented during the export / JSON generation.  

I'm actually in the process of doing a big update to the tool, to include tree view support (ease of object visibility in subscriptions have resources across multiple data centers), and I have resolved this in that build by escalating the target data center location to be obtained as input before the export process executes.  These changes are underway in my fork, as should be pulled in the near future when I get done with the updates I have envisioned.

![capture](https://cloud.githubusercontent.com/assets/16927960/20550545/f233dc98-b0f3-11e6-83e3-c871d888c423.PNG)

**Comment by singhkays** [comment]
@PauloRamosGit Could you take a look at this issue?

**Comment by PauloRamosGit** [comment]
@ssugar  Sorry for this unacceptable delay.
This behavior is "by design". We always export the current location of the resource. This is to avoid problems when you are exporting resources from multiple locations.

@rsanderson2350  That is an interesting layout.
