### ISSUE TITLE
Exported template puts VMs into default Availability Set which may be invalid

### ISSUE THREAD

**Issue by tomhollander** [Azure/classic-iaas-resourcemanager-migration#9]
I created a template from 2 ASM VMs, neither of which was in an avaialbility set, and each contained in their own VNETs.

The template that MigAz exported created a default availability set and put both of these VMs into it. The template deployment failed as it's not valid to put VMs in different subnets into the same availability set.

Ideally the tool should check whether or not the ASM VMs are in availability sets and mirror the configuration in the exported template.

**Comment by PauloRamosGit** [comment]
That you Tom for reporting this.
Let me recap the scenario: two VMs inside the same cloud service but using different subnets, without availability sets. Correct?
Just one additional question: do you have endpoints defined on both VMs?

**Comment by tomhollander** [comment]
No, 2 VMs in 2 Cloud Services in 2 VNETs. But the tool still tried putting them into a single Availability Set.
Yes there are endpoints on both VMs.

**Comment by singhkays** [comment]
#11 merged, closing
